### PR TITLE
Add examples for 1.4 Audio Selection and Volume Indicator features

### PR DESCRIPTION
**Pull request by ryan-rowland**
@mroberts @mmalavalli Please take a look. These changes should be propagated across all `client-quickstart-` repositories when 1.4 goes live. There's currently an ngrok tunnel serving these from my laptop here:
https://f9e660e9.ngrok.io/

Note that you will need to be on VPN to access it as it's currently pointing to RC2 in dev.

### CODE REVIEW

**Comment by manjeshbhargav** [comment]
@ryan-rowland When I click on the `Seeing unknown devices?` link, nothing happens. Is it because once the device lists are populated with named devices you disable it?

**Comment by manjeshbhargav** [comment]
@ryan-rowland Apart from that one question, LGTM.

**Comment by dprothero** [comment]
LGTM - will hold off merging until 1.4 is released

**Comment by dprothero** [comment]
+1

**Comment by piranna** [comment]
Any update on this?

**Comment by piranna** [comment]
Thank you :-)

**Pull request merged**
